language:    erlang
otp_release: 17.0

env:
  - ELIXIR=v0.14.0
  - ELIXIR=v0.14.1

before_install:
  - mkdir -p vendor/elixir
  - wget -q "https://github.com/elixir-lang/elixir/releases/download/$ELIXIR/Precompiled.zip" && unzip -qq Precompiled.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test

install: mix deps.get
script:  mix test
